//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.19 at 08:51:02 AM CEST 
//


package fr.urssaf.image.sae.integration.ihmweb.modele.soapfaults;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListeSoapFaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListeSoapFaultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SoapFault" type="{http://www.cirtil.fr/saeIntegration/soapFaults}SoapFaultType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListeSoapFaultType", propOrder = {
    "soapFault"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class ListeSoapFaultType {

    @XmlElement(name = "SoapFault")
    protected List<SoapFaultType> soapFault;

    /**
     * Gets the value of the soapFault property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the soapFault property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoapFault().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoapFaultType }
     * 
     * 
     */
    public List<SoapFaultType> getSoapFault() {
        if (soapFault == null) {
            soapFault = new ArrayList<SoapFaultType>();
        }
        return this.soapFault;
    }

}
