//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.02 at 01:02:31 PM CET 
//


package fr.urssaf.image.commons.spring.batch.model.xml.bibliotheque;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import fr.urssaf.image.commons.spring.batch.model.xml.livre.LivresType;


/**
 * <p>Java class for BibliothequeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BibliothequeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adresse">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="livres" type="{http://www.cirtil.fr/sae/common/bibliotheque_element}LivresType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BibliothequeType", propOrder = {
    "adresse",
    "livres"
})
@SuppressWarnings("PMD")
public class BibliothequeType {

    @XmlElement(required = true)
    protected String adresse;
    @XmlElement(required = true)
    protected LivresType livres;

    /**
     * Gets the value of the adresse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresse(String value) {
        this.adresse = value;
    }

    /**
     * Gets the value of the livres property.
     * 
     * @return
     *     possible object is
     *     {@link LivresType }
     *     
     */
    public LivresType getLivres() {
        return livres;
    }

    /**
     * Sets the value of the livres property.
     * 
     * @param value
     *     allowed object is
     *     {@link LivresType }
     *     
     */
    public void setLivres(LivresType value) {
        this.livres = value;
    }

}
