//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.02 at 01:02:31 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cirtil.fr/sae/common/bibliotheque", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.urssaf.image.commons.spring.batch.model.xml.bibliotheque;
