//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:23:26 AM CET 
//


package un.unece.uncefact.codelist.draft.daf.descriptionlevelcode._2009_08_18;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LevelDescriptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LevelDescriptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="class"/>
 *     &lt;enumeration value="collection"/>
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="fonds"/>
 *     &lt;enumeration value="item"/>
 *     &lt;enumeration value="recordgrp"/>
 *     &lt;enumeration value="series"/>
 *     &lt;enumeration value="subfonds"/>
 *     &lt;enumeration value="subgrp"/>
 *     &lt;enumeration value="subseries"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LevelDescriptionType", namespace = "urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18")
@XmlEnum
public enum LevelDescriptionType {


    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Classe&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Cette valeur, issue de la tradition archivistique allemande, ne correspond pas pour l'instant aux pratiques archivistiques françaises&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("class")
    CLASS("class"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Collection&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Réunion artificielle de documents en fonction de critères communs liés à leur contenu ou à leur support, sans considération de leur provenance, par opposition au fonds d'archives constitué de façon organique&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("collection")
    COLLECTION("collection"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Dossier&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ensemble de documents regroupés, soit par le producteur pour son usage courant, soit dans le processus du classement d'archives, parce qu'ils concernent un même sujet ou une même affaire; le dossier est ordinairement l'unité de base à l'intérieur d'une série organique&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("file")
    FILE("file"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Fonds&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ensemble de documents quels que soit leur type et leur support, créé ou reçu de manière organique et utilisé par une personne physique ou morale dans l'exercice de ses activités&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("fonds")
    FONDS("fonds"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Item&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;plus petite unité documentaire, par exemple une lettre, un mémoire, un rapport, une photographie, un enregistrement sonore&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("item")
    ITEM("item"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Groupe de documents&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;niveau de description intermédiaire qui ne correspond pas à une division organique (sous-fonds, série ou sous-série organique); parties au sein d'une collection, versements,  épaves d'un fonds, subdivisions de fonds dont on ne connait pas la nature exacte, sous-ensemble classés thématiquement&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("recordgrp")
    RECORDGRP("recordgrp"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Serie organique&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;division organique d'un fonds, correspondant à un ensemble de dossiers maintenus groupés parce qu'ils résultent d'une même activité, se rapportent à une même fonction ou à un même sujet ou revêtent une même forme&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("series")
    SERIES("series"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Sous fonds&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;division organique d'un fonds correspondant aux divisions administratives de l'institution ou de l'organisme producteur, ou, à défaut,  à un regroupement géographique, chronologique, fonctionnel ou autre des documents; quand le producteur a une structure hiérarchique complexe , chaque sous-fonds est lui-même subdivisé, autant que nécessaire pour refléter les niveaux hiérarchiques&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("subfonds")
    SUBFONDS("subfonds"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Sous-groupe de documents&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;subdivision du groupe de documents&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("subgrp")
    SUBGRP("subgrp"),

    /**
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Sous-série organique&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 			      
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:accessRestrictionCode:2009-08-18" xmlns:clmDAFDescriptionLevelCode="urn:un:unece:uncefact:codelist:draft:DAF:descriptionLevelCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;subdivision de la série organique&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 		      
     * 
     */
    @XmlEnumValue("subseries")
    SUBSERIES("subseries");
    private final String value;

    LevelDescriptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LevelDescriptionType fromValue(String v) {
        for (LevelDescriptionType c: LevelDescriptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
