package fr.urssaf.image.commons.xml.castor.modele;

// Generated 25 mai 2010 17:42:23 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auteur generated by hbm2java
 */
@Entity
@Table(name = "auteur")
public class Auteur implements java.io.Serializable {

	
	/**
    * 
    */
   private static final long serialVersionUID = 1L;
   @SuppressWarnings("PMD.ShortVariable") 
	private Integer id;
	private String nom;
	private Set<Document> documents = new HashSet<Document>(0);

	public Auteur() {
		//constructeur vide
	}

	public Auteur(String nom) {
		this.nom = nom;
	}

	public Auteur(String nom, Set<Document> documents) {
		this.nom = nom;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@SuppressWarnings("PMD.ShortVariable") 
	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false, length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auteur")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
