//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.05 at 04:39:20 PM CEST 
//


package fr.urssaf.image.sae.integration.ihmweb.modele.refmeta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetadonneeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetadonneeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codeLong" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codeCourt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="archivablePossible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="archivableObligatoire" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="consulteeParDefaut" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="consultable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="critereRecherche" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="obligatoireAuStockage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="typeDfce" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetadonneeType", propOrder = {
    "codeLong",
    "codeCourt",
    "archivablePossible",
    "archivableObligatoire",
    "consulteeParDefaut",
    "consultable",
    "critereRecherche",
    "client",
    "obligatoireAuStockage",
    "typeDfce"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class MetadonneeType {

    @XmlElement(required = true)
    protected String codeLong;
    @XmlElement(required = true)
    protected String codeCourt;
    protected boolean archivablePossible;
    protected boolean archivableObligatoire;
    protected boolean consulteeParDefaut;
    protected boolean consultable;
    protected boolean critereRecherche;
    protected boolean client;
    protected boolean obligatoireAuStockage;
    @XmlElement(required = true)
    protected String typeDfce;

    /**
     * Gets the value of the codeLong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeLong() {
        return codeLong;
    }

    /**
     * Sets the value of the codeLong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeLong(String value) {
        this.codeLong = value;
    }

    /**
     * Gets the value of the codeCourt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeCourt() {
        return codeCourt;
    }

    /**
     * Sets the value of the codeCourt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeCourt(String value) {
        this.codeCourt = value;
    }

    /**
     * Gets the value of the archivablePossible property.
     * 
     */
    public boolean isArchivablePossible() {
        return archivablePossible;
    }

    /**
     * Sets the value of the archivablePossible property.
     * 
     */
    public void setArchivablePossible(boolean value) {
        this.archivablePossible = value;
    }

    /**
     * Gets the value of the archivableObligatoire property.
     * 
     */
    public boolean isArchivableObligatoire() {
        return archivableObligatoire;
    }

    /**
     * Sets the value of the archivableObligatoire property.
     * 
     */
    public void setArchivableObligatoire(boolean value) {
        this.archivableObligatoire = value;
    }

    /**
     * Gets the value of the consulteeParDefaut property.
     * 
     */
    public boolean isConsulteeParDefaut() {
        return consulteeParDefaut;
    }

    /**
     * Sets the value of the consulteeParDefaut property.
     * 
     */
    public void setConsulteeParDefaut(boolean value) {
        this.consulteeParDefaut = value;
    }

    /**
     * Gets the value of the consultable property.
     * 
     */
    public boolean isConsultable() {
        return consultable;
    }

    /**
     * Sets the value of the consultable property.
     * 
     */
    public void setConsultable(boolean value) {
        this.consultable = value;
    }

    /**
     * Gets the value of the critereRecherche property.
     * 
     */
    public boolean isCritereRecherche() {
        return critereRecherche;
    }

    /**
     * Sets the value of the critereRecherche property.
     * 
     */
    public void setCritereRecherche(boolean value) {
        this.critereRecherche = value;
    }

    /**
     * Gets the value of the client property.
     * 
     */
    public boolean isClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     */
    public void setClient(boolean value) {
        this.client = value;
    }

    /**
     * Gets the value of the obligatoireAuStockage property.
     * 
     */
    public boolean isObligatoireAuStockage() {
        return obligatoireAuStockage;
    }

    /**
     * Sets the value of the obligatoireAuStockage property.
     * 
     */
    public void setObligatoireAuStockage(boolean value) {
        this.obligatoireAuStockage = value;
    }

    /**
     * Gets the value of the typeDfce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeDfce() {
        return typeDfce;
    }

    /**
     * Sets the value of the typeDfce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeDfce(String value) {
        this.typeDfce = value;
    }

}
