//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:23:26 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1")
package fr.gouv.ae.archive.draft.standard_echange_v0_2.qualifieddatatype._1;
