package fr.urssaf.image.commons.webservice.exemple.rpc.encoded.modele;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon May 31 12:51:22 CEST 2010
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://encoded.rpc.service.exemple.spring.webservice.commons.image.urssaf.fr/", name = "DocService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DocService {

    @WebResult(name = "return", targetNamespace = "http://encoded.rpc.service.exemple.spring.webservice.commons.image.urssaf.fr/", partName = "return")
    @WebMethod
    public DocumentArray allDocuments();
}
