package fr.urssaf.image.commons.dao.spring.exemple.modele;

// Generated 25 mai 2010 17:42:23 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocumentView generated by hbm2java
 */
@Entity
@Table(name = "document_view")
@SuppressWarnings("PMD.ShortVariable") 
public class DocumentView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String titre;
	private Date date;
	private String auteur;

	public DocumentView() {
		//constructeur vide
	}

	public DocumentView(int id, String titre, Date date) {
		this.id = id;
		this.titre = titre;
		this.date = date;
	}

	public DocumentView(int id, String titre, Date date, String auteur) {
		this.id = id;
		this.titre = titre;
		this.date = date;
		this.auteur = auteur;
	}

	@Id
	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "auteur", length = 45)
	public String getAuteur() {
		return this.auteur;
	}

	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

}
