package fr.urssaf.image.commons.springsecurity.acl.model;

// Generated 7 juil. 2011 14:19:27 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "SPRINGSECURITY-ACL")
public class Person implements java.io.Serializable {

   private static final long serialVersionUID = 1L;

   @SuppressWarnings("PMD.ShortVariable")
   private Integer id;
   private String lastname;
   private String firstname;
   private Set<Publication> publications = new HashSet<Publication>(0);

   public Person() {
      // constructeur par défaut
   }

   public Person(String lastname, String firstname) {
      this.lastname = lastname;
      this.firstname = firstname;
   }

   public Person(String lastname, String firstname,
         Set<Publication> publications) {
      this.lastname = lastname;
      this.firstname = firstname;
      this.publications = publications;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "id", unique = true, nullable = false)
   public Integer getId() {
      return this.id;
   }

   @SuppressWarnings("PMD.ShortVariable")
   public void setId(Integer id) {
      this.id = id;
   }

   @Column(name = "lastname", nullable = false, length = 45)
   public String getLastname() {
      return this.lastname;
   }

   public void setLastname(String lastname) {
      this.lastname = lastname;
   }

   @Column(name = "firstname", nullable = false, length = 45)
   public String getFirstname() {
      return this.firstname;
   }

   public void setFirstname(String firstname) {
      this.firstname = firstname;
   }

   @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "person")
   public Set<Publication> getPublications() {
      return this.publications;
   }

   public void setPublications(Set<Publication> publications) {
      this.publications = publications;
   }

}
