package fr.urssaf.image.commons.springsecurity.acl.model;

// Generated 7 juil. 2011 14:19:27 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Publication generated by hbm2java
 */
@Entity
@Table(name = "publication", catalog = "SPRINGSECURITY-ACL")
public class Publication implements java.io.Serializable {

   private static final long serialVersionUID = 1L;

   @SuppressWarnings("PMD.ShortVariable")
   private Integer id;
   private Person author;
   private String title;

   public Publication() {
      //constructeur par défaut
   }

   public Publication(Person author, String title) {
      this.author = author;
      this.title = title;
   }

   @Id
   @GeneratedValue(strategy = IDENTITY)
   @Column(name = "id", unique = true, nullable = false)
   public Integer getId() {
      return this.id;
   }

   @SuppressWarnings("PMD.ShortVariable")
   public void setId(Integer id) {
      this.id = id;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_author", nullable = false)
   public Person getAuthor() {
      return this.author;
   }

   public void setAuthor(Person author) {
      this.author = author;
   }

   @Column(name = "title", nullable = false, length = 45)
   public String getTitle() {
      return this.title;
   }

   public void setTitle(String title) {
      this.title = title;
   }

}
