//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccuseReception complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccuseReception">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Acceptation" type="{http://xml.sandre.eaufrance.fr/message/1}Acceptation"/>
 *         &lt;element name="CodeScenario" type="{http://xml.sandre.eaufrance.fr/message/1}CodeScenario"/>
 *         &lt;element name="VersionScenario" type="{http://xml.sandre.eaufrance.fr/message/1}VersionScenario"/>
 *         &lt;element name="NomScenario" type="{http://xml.sandre.eaufrance.fr/message/1}NomScenario"/>
 *         &lt;element name="DateCreationFichier" type="{http://xml.sandre.eaufrance.fr/message/1}DateCreationFichier" minOccurs="0"/>
 *         &lt;element name="ReferenceFichierEnvoi" type="{http://xml.sandre.eaufrance.fr/message/1}ReferenceFichierEnvoi" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="DateDebutReference" type="{http://xml.sandre.eaufrance.fr/message/1}DateDebutReference" minOccurs="0"/>
 *             &lt;element name="DateFinReference" type="{http://xml.sandre.eaufrance.fr/message/1}DateFinReference" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="DateDebutDonneesTransmises" type="{http://xml.sandre.eaufrance.fr/message/1}DateDebutDonneesTransmises" minOccurs="0"/>
 *             &lt;element name="DateFinDonneesTransmises" type="{http://xml.sandre.eaufrance.fr/message/1}DateFinDonneesTransmises" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Erreur" type="{http://xml.sandre.eaufrance.fr/message/1}Erreur" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccuseReception", propOrder = {
    "acceptation",
    "codeScenario",
    "versionScenario",
    "nomScenario",
    "dateCreationFichier",
    "referenceFichierEnvoi",
    "dateDebutReference",
    "dateFinReference",
    "dateDebutDonneesTransmises",
    "dateFinDonneesTransmises",
    "erreur"
})
public class AccuseReception {

    @XmlElement(name = "Acceptation", required = true)
    protected Acceptation acceptation;
    @XmlElement(name = "CodeScenario", required = true)
    protected CodeScenario codeScenario;
    @XmlElement(name = "VersionScenario", required = true)
    protected VersionScenario versionScenario;
    @XmlElement(name = "NomScenario", required = true)
    protected NomScenario nomScenario;
    @XmlElement(name = "DateCreationFichier")
    protected DateCreationFichier dateCreationFichier;
    @XmlElement(name = "ReferenceFichierEnvoi")
    protected ReferenceFichierEnvoi referenceFichierEnvoi;
    @XmlElement(name = "DateDebutReference")
    protected DateDebutReference dateDebutReference;
    @XmlElement(name = "DateFinReference")
    protected DateFinReference dateFinReference;
    @XmlElement(name = "DateDebutDonneesTransmises")
    protected DateDebutDonneesTransmises dateDebutDonneesTransmises;
    @XmlElement(name = "DateFinDonneesTransmises")
    protected DateFinDonneesTransmises dateFinDonneesTransmises;
    @XmlElement(name = "Erreur")
    protected List<Erreur> erreur;

    /**
     * Gets the value of the acceptation property.
     * 
     * @return
     *     possible object is
     *     {@link Acceptation }
     *     
     */
    public Acceptation getAcceptation() {
        return acceptation;
    }

    /**
     * Sets the value of the acceptation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Acceptation }
     *     
     */
    public void setAcceptation(Acceptation value) {
        this.acceptation = value;
    }

    /**
     * Gets the value of the codeScenario property.
     * 
     * @return
     *     possible object is
     *     {@link CodeScenario }
     *     
     */
    public CodeScenario getCodeScenario() {
        return codeScenario;
    }

    /**
     * Sets the value of the codeScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeScenario }
     *     
     */
    public void setCodeScenario(CodeScenario value) {
        this.codeScenario = value;
    }

    /**
     * Gets the value of the versionScenario property.
     * 
     * @return
     *     possible object is
     *     {@link VersionScenario }
     *     
     */
    public VersionScenario getVersionScenario() {
        return versionScenario;
    }

    /**
     * Sets the value of the versionScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionScenario }
     *     
     */
    public void setVersionScenario(VersionScenario value) {
        this.versionScenario = value;
    }

    /**
     * Gets the value of the nomScenario property.
     * 
     * @return
     *     possible object is
     *     {@link NomScenario }
     *     
     */
    public NomScenario getNomScenario() {
        return nomScenario;
    }

    /**
     * Sets the value of the nomScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomScenario }
     *     
     */
    public void setNomScenario(NomScenario value) {
        this.nomScenario = value;
    }

    /**
     * Gets the value of the dateCreationFichier property.
     * 
     * @return
     *     possible object is
     *     {@link DateCreationFichier }
     *     
     */
    public DateCreationFichier getDateCreationFichier() {
        return dateCreationFichier;
    }

    /**
     * Sets the value of the dateCreationFichier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCreationFichier }
     *     
     */
    public void setDateCreationFichier(DateCreationFichier value) {
        this.dateCreationFichier = value;
    }

    /**
     * Gets the value of the referenceFichierEnvoi property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceFichierEnvoi }
     *     
     */
    public ReferenceFichierEnvoi getReferenceFichierEnvoi() {
        return referenceFichierEnvoi;
    }

    /**
     * Sets the value of the referenceFichierEnvoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceFichierEnvoi }
     *     
     */
    public void setReferenceFichierEnvoi(ReferenceFichierEnvoi value) {
        this.referenceFichierEnvoi = value;
    }

    /**
     * Gets the value of the dateDebutReference property.
     * 
     * @return
     *     possible object is
     *     {@link DateDebutReference }
     *     
     */
    public DateDebutReference getDateDebutReference() {
        return dateDebutReference;
    }

    /**
     * Sets the value of the dateDebutReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateDebutReference }
     *     
     */
    public void setDateDebutReference(DateDebutReference value) {
        this.dateDebutReference = value;
    }

    /**
     * Gets the value of the dateFinReference property.
     * 
     * @return
     *     possible object is
     *     {@link DateFinReference }
     *     
     */
    public DateFinReference getDateFinReference() {
        return dateFinReference;
    }

    /**
     * Sets the value of the dateFinReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFinReference }
     *     
     */
    public void setDateFinReference(DateFinReference value) {
        this.dateFinReference = value;
    }

    /**
     * Gets the value of the dateDebutDonneesTransmises property.
     * 
     * @return
     *     possible object is
     *     {@link DateDebutDonneesTransmises }
     *     
     */
    public DateDebutDonneesTransmises getDateDebutDonneesTransmises() {
        return dateDebutDonneesTransmises;
    }

    /**
     * Sets the value of the dateDebutDonneesTransmises property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateDebutDonneesTransmises }
     *     
     */
    public void setDateDebutDonneesTransmises(DateDebutDonneesTransmises value) {
        this.dateDebutDonneesTransmises = value;
    }

    /**
     * Gets the value of the dateFinDonneesTransmises property.
     * 
     * @return
     *     possible object is
     *     {@link DateFinDonneesTransmises }
     *     
     */
    public DateFinDonneesTransmises getDateFinDonneesTransmises() {
        return dateFinDonneesTransmises;
    }

    /**
     * Sets the value of the dateFinDonneesTransmises property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFinDonneesTransmises }
     *     
     */
    public void setDateFinDonneesTransmises(DateFinDonneesTransmises value) {
        this.dateFinDonneesTransmises = value;
    }

    /**
     * Gets the value of the erreur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the erreur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErreur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Erreur }
     * 
     * 
     */
    public List<Erreur> getErreur() {
        if (erreur == null) {
            erreur = new ArrayList<Erreur>();
        }
        return this.erreur;
    }

}
