//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur.Contact }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur.Contact createScenarioEmetteurContact() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur.Contact();
    }

    /**
     * Create an instance of {@link ReferenceFichier }
     * 
     */
    public ReferenceFichier createReferenceFichier() {
        return new ReferenceFichier();
    }

    /**
     * Create an instance of {@link DateDebutReference }
     * 
     */
    public DateDebutReference createDateDebutReference() {
        return new DateDebutReference();
    }

    /**
     * Create an instance of {@link ReferenceFichierEnvoi }
     * 
     */
    public ReferenceFichierEnvoi createReferenceFichierEnvoi() {
        return new ReferenceFichierEnvoi();
    }

    /**
     * Create an instance of {@link ACQ.Scenario.Emetteur.Contact }
     * 
     */
    public ACQ.Scenario.Emetteur.Contact createACQScenarioEmetteurContact() {
        return new ACQ.Scenario.Emetteur.Contact();
    }

    /**
     * Create an instance of {@link DateFinDonneesTransmises }
     * 
     */
    public DateFinDonneesTransmises createDateFinDonneesTransmises() {
        return new DateFinDonneesTransmises();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire.Service }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire.Service createScenarioDestinataireService() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire.Service();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur createScenarioEmetteur() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire.Contact }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire.Contact createScenarioDestinataireContact() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire.Contact();
    }

    /**
     * Create an instance of {@link CodeScenario }
     * 
     */
    public CodeScenario createCodeScenario() {
        return new CodeScenario();
    }

    /**
     * Create an instance of {@link ACQ.AccuseReception.Erreur }
     * 
     */
    public ACQ.AccuseReception.Erreur createACQAccuseReceptionErreur() {
        return new ACQ.AccuseReception.Erreur();
    }

    /**
     * Create an instance of {@link Referentiel }
     * 
     */
    public Referentiel createReferentiel() {
        return new Referentiel();
    }

    /**
     * Create an instance of {@link NomScenario }
     * 
     */
    public NomScenario createNomScenario() {
        return new NomScenario();
    }

    /**
     * Create an instance of {@link VersionScenario }
     * 
     */
    public VersionScenario createVersionScenario() {
        return new VersionScenario();
    }

    /**
     * Create an instance of {@link ACQ }
     * 
     */
    public ACQ createACQ() {
        return new ACQ();
    }

    /**
     * Create an instance of {@link DescriptifErreur }
     * 
     */
    public DescriptifErreur createDescriptifErreur() {
        return new DescriptifErreur();
    }

    /**
     * Create an instance of {@link DateCreationFichier }
     * 
     */
    public DateCreationFichier createDateCreationFichier() {
        return new DateCreationFichier();
    }

    /**
     * Create an instance of {@link CdContexte }
     * 
     */
    public CdContexte createCdContexte() {
        return new CdContexte();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.AccuseReception }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.AccuseReception createAccuseReception() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.AccuseReception();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario createScenario() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire createScenarioDestinataire() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Destinataire();
    }

    /**
     * Create an instance of {@link ACQ.Scenario }
     * 
     */
    public ACQ.Scenario createACQScenario() {
        return new ACQ.Scenario();
    }

    /**
     * Create an instance of {@link ACQ.Scenario.Emetteur }
     * 
     */
    public ACQ.Scenario.Emetteur createACQScenarioEmetteur() {
        return new ACQ.Scenario.Emetteur();
    }

    /**
     * Create an instance of {@link ACQ.Scenario.Emetteur.Service }
     * 
     */
    public ACQ.Scenario.Emetteur.Service createACQScenarioEmetteurService() {
        return new ACQ.Scenario.Emetteur.Service();
    }

    /**
     * Create an instance of {@link ACQ.AccuseReception }
     * 
     */
    public ACQ.AccuseReception createACQAccuseReception() {
        return new ACQ.AccuseReception();
    }

    /**
     * Create an instance of {@link LbContexte }
     * 
     */
    public LbContexte createLbContexte() {
        return new LbContexte();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur.Service }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur.Service createScenarioEmetteurService() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Scenario.Emetteur.Service();
    }

    /**
     * Create an instance of {@link DateFinReference }
     * 
     */
    public DateFinReference createDateFinReference() {
        return new DateFinReference();
    }

    /**
     * Create an instance of {@link ACQ.Scenario.Destinataire.Service }
     * 
     */
    public ACQ.Scenario.Destinataire.Service createACQScenarioDestinataireService() {
        return new ACQ.Scenario.Destinataire.Service();
    }

    /**
     * Create an instance of {@link CdErreur }
     * 
     */
    public CdErreur createCdErreur() {
        return new CdErreur();
    }

    /**
     * Create an instance of {@link ACQ.Scenario.Destinataire.Contact }
     * 
     */
    public ACQ.Scenario.Destinataire.Contact createACQScenarioDestinataireContact() {
        return new ACQ.Scenario.Destinataire.Contact();
    }

    /**
     * Create an instance of {@link Acceptation }
     * 
     */
    public Acceptation createAcceptation() {
        return new Acceptation();
    }

    /**
     * Create an instance of {@link fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Erreur }
     * 
     */
    public fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Erreur createErreur() {
        return new fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.Erreur();
    }

    /**
     * Create an instance of {@link ACQ.Scenario.Destinataire }
     * 
     */
    public ACQ.Scenario.Destinataire createACQScenarioDestinataire() {
        return new ACQ.Scenario.Destinataire();
    }

    /**
     * Create an instance of {@link DateDebutDonneesTransmises }
     * 
     */
    public DateDebutDonneesTransmises createDateDebutDonneesTransmises() {
        return new DateDebutDonneesTransmises();
    }

    /**
     * Create an instance of {@link LocationErreur }
     * 
     */
    public LocationErreur createLocationErreur() {
        return new LocationErreur();
    }

}
