//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.BpIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.CdIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.CommentairesIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.DepIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.ImmoIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.LieuIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.MnIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomContact;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomService;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.RueIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.VilleIntervenant;


/**
 * <p>Java class for Scenario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Scenario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodeScenario" type="{http://xml.sandre.eaufrance.fr/message/1}CodeScenario"/>
 *         &lt;element name="VersionScenario" type="{http://xml.sandre.eaufrance.fr/message/1}VersionScenario"/>
 *         &lt;element name="NomScenario" type="{http://xml.sandre.eaufrance.fr/message/1}NomScenario"/>
 *         &lt;element name="DateCreationFichier" type="{http://xml.sandre.eaufrance.fr/message/1}DateCreationFichier" minOccurs="0"/>
 *         &lt;element name="ReferenceFichierEnvoi" type="{http://xml.sandre.eaufrance.fr/message/1}ReferenceFichierEnvoi" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="DateDebutReference" type="{http://xml.sandre.eaufrance.fr/message/1}DateDebutReference" minOccurs="0"/>
 *             &lt;element name="DateFinReference" type="{http://xml.sandre.eaufrance.fr/message/1}DateFinReference" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="DateDebutDonneesTransmises" type="{http://xml.sandre.eaufrance.fr/message/1}DateDebutDonneesTransmises" minOccurs="0"/>
 *             &lt;element name="DateFinDonneesTransmises" type="{http://xml.sandre.eaufrance.fr/message/1}DateFinDonneesTransmises" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Emetteur" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CdIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CdIntervenant"/>
 *                   &lt;element name="NomIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}NomIntervenant" minOccurs="0"/>
 *                   &lt;element name="MnIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}MnIntervenant" minOccurs="0"/>
 *                   &lt;element name="BpIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}BpIntervenant" minOccurs="0"/>
 *                   &lt;element name="ImmoIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}ImmoIntervenant" minOccurs="0"/>
 *                   &lt;element name="RueIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}RueIntervenant" minOccurs="0"/>
 *                   &lt;element name="LieuIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}LieuIntervenant" minOccurs="0"/>
 *                   &lt;element name="VilleIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}VilleIntervenant" minOccurs="0"/>
 *                   &lt;element name="DepIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DepIntervenant" minOccurs="0"/>
 *                   &lt;element name="CommentairesIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CommentairesIntervenant" minOccurs="0"/>
 *                   &lt;element name="Service" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Contact" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Destinataire" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CdIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CdIntervenant"/>
 *                   &lt;element name="NomIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}NomIntervenant" minOccurs="0"/>
 *                   &lt;element name="MnIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}MnIntervenant" minOccurs="0"/>
 *                   &lt;element name="BpIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}BpIntervenant" minOccurs="0"/>
 *                   &lt;element name="ImmoIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}ImmoIntervenant" minOccurs="0"/>
 *                   &lt;element name="RueIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}RueIntervenant" minOccurs="0"/>
 *                   &lt;element name="LieuIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}LieuIntervenant" minOccurs="0"/>
 *                   &lt;element name="VilleIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}VilleIntervenant" minOccurs="0"/>
 *                   &lt;element name="DepIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DepIntervenant" minOccurs="0"/>
 *                   &lt;element name="CommentairesIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CommentairesIntervenant" minOccurs="0"/>
 *                   &lt;element name="Service" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Contact" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Referentiel" type="{http://xml.sandre.eaufrance.fr/message/1}Referentiel" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Scenario", propOrder = {
    "codeScenario",
    "versionScenario",
    "nomScenario",
    "dateCreationFichier",
    "referenceFichierEnvoi",
    "dateDebutReference",
    "dateFinReference",
    "dateDebutDonneesTransmises",
    "dateFinDonneesTransmises",
    "emetteur",
    "destinataire",
    "referentiel"
})
public class Scenario {

    @XmlElement(name = "CodeScenario", required = true)
    protected CodeScenario codeScenario;
    @XmlElement(name = "VersionScenario", required = true)
    protected VersionScenario versionScenario;
    @XmlElement(name = "NomScenario", required = true)
    protected NomScenario nomScenario;
    @XmlElement(name = "DateCreationFichier")
    protected DateCreationFichier dateCreationFichier;
    @XmlElement(name = "ReferenceFichierEnvoi")
    protected ReferenceFichierEnvoi referenceFichierEnvoi;
    @XmlElement(name = "DateDebutReference")
    protected DateDebutReference dateDebutReference;
    @XmlElement(name = "DateFinReference")
    protected DateFinReference dateFinReference;
    @XmlElement(name = "DateDebutDonneesTransmises")
    protected DateDebutDonneesTransmises dateDebutDonneesTransmises;
    @XmlElement(name = "DateFinDonneesTransmises")
    protected DateFinDonneesTransmises dateFinDonneesTransmises;
    @XmlElement(name = "Emetteur")
    protected Scenario.Emetteur emetteur;
    @XmlElement(name = "Destinataire")
    protected Scenario.Destinataire destinataire;
    @XmlElement(name = "Referentiel")
    protected List<Referentiel> referentiel;

    /**
     * Gets the value of the codeScenario property.
     * 
     * @return
     *     possible object is
     *     {@link CodeScenario }
     *     
     */
    public CodeScenario getCodeScenario() {
        return codeScenario;
    }

    /**
     * Sets the value of the codeScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeScenario }
     *     
     */
    public void setCodeScenario(CodeScenario value) {
        this.codeScenario = value;
    }

    /**
     * Gets the value of the versionScenario property.
     * 
     * @return
     *     possible object is
     *     {@link VersionScenario }
     *     
     */
    public VersionScenario getVersionScenario() {
        return versionScenario;
    }

    /**
     * Sets the value of the versionScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionScenario }
     *     
     */
    public void setVersionScenario(VersionScenario value) {
        this.versionScenario = value;
    }

    /**
     * Gets the value of the nomScenario property.
     * 
     * @return
     *     possible object is
     *     {@link NomScenario }
     *     
     */
    public NomScenario getNomScenario() {
        return nomScenario;
    }

    /**
     * Sets the value of the nomScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomScenario }
     *     
     */
    public void setNomScenario(NomScenario value) {
        this.nomScenario = value;
    }

    /**
     * Gets the value of the dateCreationFichier property.
     * 
     * @return
     *     possible object is
     *     {@link DateCreationFichier }
     *     
     */
    public DateCreationFichier getDateCreationFichier() {
        return dateCreationFichier;
    }

    /**
     * Sets the value of the dateCreationFichier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCreationFichier }
     *     
     */
    public void setDateCreationFichier(DateCreationFichier value) {
        this.dateCreationFichier = value;
    }

    /**
     * Gets the value of the referenceFichierEnvoi property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceFichierEnvoi }
     *     
     */
    public ReferenceFichierEnvoi getReferenceFichierEnvoi() {
        return referenceFichierEnvoi;
    }

    /**
     * Sets the value of the referenceFichierEnvoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceFichierEnvoi }
     *     
     */
    public void setReferenceFichierEnvoi(ReferenceFichierEnvoi value) {
        this.referenceFichierEnvoi = value;
    }

    /**
     * Gets the value of the dateDebutReference property.
     * 
     * @return
     *     possible object is
     *     {@link DateDebutReference }
     *     
     */
    public DateDebutReference getDateDebutReference() {
        return dateDebutReference;
    }

    /**
     * Sets the value of the dateDebutReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateDebutReference }
     *     
     */
    public void setDateDebutReference(DateDebutReference value) {
        this.dateDebutReference = value;
    }

    /**
     * Gets the value of the dateFinReference property.
     * 
     * @return
     *     possible object is
     *     {@link DateFinReference }
     *     
     */
    public DateFinReference getDateFinReference() {
        return dateFinReference;
    }

    /**
     * Sets the value of the dateFinReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFinReference }
     *     
     */
    public void setDateFinReference(DateFinReference value) {
        this.dateFinReference = value;
    }

    /**
     * Gets the value of the dateDebutDonneesTransmises property.
     * 
     * @return
     *     possible object is
     *     {@link DateDebutDonneesTransmises }
     *     
     */
    public DateDebutDonneesTransmises getDateDebutDonneesTransmises() {
        return dateDebutDonneesTransmises;
    }

    /**
     * Sets the value of the dateDebutDonneesTransmises property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateDebutDonneesTransmises }
     *     
     */
    public void setDateDebutDonneesTransmises(DateDebutDonneesTransmises value) {
        this.dateDebutDonneesTransmises = value;
    }

    /**
     * Gets the value of the dateFinDonneesTransmises property.
     * 
     * @return
     *     possible object is
     *     {@link DateFinDonneesTransmises }
     *     
     */
    public DateFinDonneesTransmises getDateFinDonneesTransmises() {
        return dateFinDonneesTransmises;
    }

    /**
     * Sets the value of the dateFinDonneesTransmises property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateFinDonneesTransmises }
     *     
     */
    public void setDateFinDonneesTransmises(DateFinDonneesTransmises value) {
        this.dateFinDonneesTransmises = value;
    }

    /**
     * Gets the value of the emetteur property.
     * 
     * @return
     *     possible object is
     *     {@link Scenario.Emetteur }
     *     
     */
    public Scenario.Emetteur getEmetteur() {
        return emetteur;
    }

    /**
     * Sets the value of the emetteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scenario.Emetteur }
     *     
     */
    public void setEmetteur(Scenario.Emetteur value) {
        this.emetteur = value;
    }

    /**
     * Gets the value of the destinataire property.
     * 
     * @return
     *     possible object is
     *     {@link Scenario.Destinataire }
     *     
     */
    public Scenario.Destinataire getDestinataire() {
        return destinataire;
    }

    /**
     * Sets the value of the destinataire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scenario.Destinataire }
     *     
     */
    public void setDestinataire(Scenario.Destinataire value) {
        this.destinataire = value;
    }

    /**
     * Gets the value of the referentiel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referentiel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferentiel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Referentiel }
     * 
     * 
     */
    public List<Referentiel> getReferentiel() {
        if (referentiel == null) {
            referentiel = new ArrayList<Referentiel>();
        }
        return this.referentiel;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CdIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CdIntervenant"/>
     *         &lt;element name="NomIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}NomIntervenant" minOccurs="0"/>
     *         &lt;element name="MnIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}MnIntervenant" minOccurs="0"/>
     *         &lt;element name="BpIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}BpIntervenant" minOccurs="0"/>
     *         &lt;element name="ImmoIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}ImmoIntervenant" minOccurs="0"/>
     *         &lt;element name="RueIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}RueIntervenant" minOccurs="0"/>
     *         &lt;element name="LieuIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}LieuIntervenant" minOccurs="0"/>
     *         &lt;element name="VilleIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}VilleIntervenant" minOccurs="0"/>
     *         &lt;element name="DepIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DepIntervenant" minOccurs="0"/>
     *         &lt;element name="CommentairesIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CommentairesIntervenant" minOccurs="0"/>
     *         &lt;element name="Service" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Contact" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cdIntervenant",
        "nomIntervenant",
        "mnIntervenant",
        "bpIntervenant",
        "immoIntervenant",
        "rueIntervenant",
        "lieuIntervenant",
        "villeIntervenant",
        "depIntervenant",
        "commentairesIntervenant",
        "service",
        "contact"
    })
    public static class Destinataire {

        @XmlElement(name = "CdIntervenant", required = true)
        protected CdIntervenant cdIntervenant;
        @XmlElement(name = "NomIntervenant")
        protected NomIntervenant nomIntervenant;
        @XmlElement(name = "MnIntervenant")
        protected MnIntervenant mnIntervenant;
        @XmlElement(name = "BpIntervenant")
        protected BpIntervenant bpIntervenant;
        @XmlElement(name = "ImmoIntervenant")
        protected ImmoIntervenant immoIntervenant;
        @XmlElement(name = "RueIntervenant")
        protected RueIntervenant rueIntervenant;
        @XmlElement(name = "LieuIntervenant")
        protected LieuIntervenant lieuIntervenant;
        @XmlElement(name = "VilleIntervenant")
        protected VilleIntervenant villeIntervenant;
        @XmlElement(name = "DepIntervenant")
        protected DepIntervenant depIntervenant;
        @XmlElement(name = "CommentairesIntervenant")
        protected CommentairesIntervenant commentairesIntervenant;
        @XmlElement(name = "Service")
        protected Scenario.Destinataire.Service service;
        @XmlElement(name = "Contact")
        protected Scenario.Destinataire.Contact contact;

        /**
         * Gets the value of the cdIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link CdIntervenant }
         *     
         */
        public CdIntervenant getCdIntervenant() {
            return cdIntervenant;
        }

        /**
         * Sets the value of the cdIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link CdIntervenant }
         *     
         */
        public void setCdIntervenant(CdIntervenant value) {
            this.cdIntervenant = value;
        }

        /**
         * Gets the value of the nomIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link NomIntervenant }
         *     
         */
        public NomIntervenant getNomIntervenant() {
            return nomIntervenant;
        }

        /**
         * Sets the value of the nomIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link NomIntervenant }
         *     
         */
        public void setNomIntervenant(NomIntervenant value) {
            this.nomIntervenant = value;
        }

        /**
         * Gets the value of the mnIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link MnIntervenant }
         *     
         */
        public MnIntervenant getMnIntervenant() {
            return mnIntervenant;
        }

        /**
         * Sets the value of the mnIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link MnIntervenant }
         *     
         */
        public void setMnIntervenant(MnIntervenant value) {
            this.mnIntervenant = value;
        }

        /**
         * Gets the value of the bpIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link BpIntervenant }
         *     
         */
        public BpIntervenant getBpIntervenant() {
            return bpIntervenant;
        }

        /**
         * Sets the value of the bpIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link BpIntervenant }
         *     
         */
        public void setBpIntervenant(BpIntervenant value) {
            this.bpIntervenant = value;
        }

        /**
         * Gets the value of the immoIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link ImmoIntervenant }
         *     
         */
        public ImmoIntervenant getImmoIntervenant() {
            return immoIntervenant;
        }

        /**
         * Sets the value of the immoIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImmoIntervenant }
         *     
         */
        public void setImmoIntervenant(ImmoIntervenant value) {
            this.immoIntervenant = value;
        }

        /**
         * Gets the value of the rueIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link RueIntervenant }
         *     
         */
        public RueIntervenant getRueIntervenant() {
            return rueIntervenant;
        }

        /**
         * Sets the value of the rueIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link RueIntervenant }
         *     
         */
        public void setRueIntervenant(RueIntervenant value) {
            this.rueIntervenant = value;
        }

        /**
         * Gets the value of the lieuIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link LieuIntervenant }
         *     
         */
        public LieuIntervenant getLieuIntervenant() {
            return lieuIntervenant;
        }

        /**
         * Sets the value of the lieuIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link LieuIntervenant }
         *     
         */
        public void setLieuIntervenant(LieuIntervenant value) {
            this.lieuIntervenant = value;
        }

        /**
         * Gets the value of the villeIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link VilleIntervenant }
         *     
         */
        public VilleIntervenant getVilleIntervenant() {
            return villeIntervenant;
        }

        /**
         * Sets the value of the villeIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link VilleIntervenant }
         *     
         */
        public void setVilleIntervenant(VilleIntervenant value) {
            this.villeIntervenant = value;
        }

        /**
         * Gets the value of the depIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link DepIntervenant }
         *     
         */
        public DepIntervenant getDepIntervenant() {
            return depIntervenant;
        }

        /**
         * Sets the value of the depIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link DepIntervenant }
         *     
         */
        public void setDepIntervenant(DepIntervenant value) {
            this.depIntervenant = value;
        }

        /**
         * Gets the value of the commentairesIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link CommentairesIntervenant }
         *     
         */
        public CommentairesIntervenant getCommentairesIntervenant() {
            return commentairesIntervenant;
        }

        /**
         * Sets the value of the commentairesIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommentairesIntervenant }
         *     
         */
        public void setCommentairesIntervenant(CommentairesIntervenant value) {
            this.commentairesIntervenant = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link Scenario.Destinataire.Service }
         *     
         */
        public Scenario.Destinataire.Service getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link Scenario.Destinataire.Service }
         *     
         */
        public void setService(Scenario.Destinataire.Service value) {
            this.service = value;
        }

        /**
         * Gets the value of the contact property.
         * 
         * @return
         *     possible object is
         *     {@link Scenario.Destinataire.Contact }
         *     
         */
        public Scenario.Destinataire.Contact getContact() {
            return contact;
        }

        /**
         * Sets the value of the contact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Scenario.Destinataire.Contact }
         *     
         */
        public void setContact(Scenario.Destinataire.Contact value) {
            this.contact = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nomContact"
        })
        public static class Contact {

            @XmlElement(name = "NomContact")
            protected NomContact nomContact;

            /**
             * Gets the value of the nomContact property.
             * 
             * @return
             *     possible object is
             *     {@link NomContact }
             *     
             */
            public NomContact getNomContact() {
                return nomContact;
            }

            /**
             * Sets the value of the nomContact property.
             * 
             * @param value
             *     allowed object is
             *     {@link NomContact }
             *     
             */
            public void setNomContact(NomContact value) {
                this.nomContact = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nomService"
        })
        public static class Service {

            @XmlElement(name = "NomService")
            protected NomService nomService;

            /**
             * Gets the value of the nomService property.
             * 
             * @return
             *     possible object is
             *     {@link NomService }
             *     
             */
            public NomService getNomService() {
                return nomService;
            }

            /**
             * Sets the value of the nomService property.
             * 
             * @param value
             *     allowed object is
             *     {@link NomService }
             *     
             */
            public void setNomService(NomService value) {
                this.nomService = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CdIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CdIntervenant"/>
     *         &lt;element name="NomIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}NomIntervenant" minOccurs="0"/>
     *         &lt;element name="MnIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}MnIntervenant" minOccurs="0"/>
     *         &lt;element name="BpIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}BpIntervenant" minOccurs="0"/>
     *         &lt;element name="ImmoIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}ImmoIntervenant" minOccurs="0"/>
     *         &lt;element name="RueIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}RueIntervenant" minOccurs="0"/>
     *         &lt;element name="LieuIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}LieuIntervenant" minOccurs="0"/>
     *         &lt;element name="VilleIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}VilleIntervenant" minOccurs="0"/>
     *         &lt;element name="DepIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DepIntervenant" minOccurs="0"/>
     *         &lt;element name="CommentairesIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CommentairesIntervenant" minOccurs="0"/>
     *         &lt;element name="Service" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Contact" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cdIntervenant",
        "nomIntervenant",
        "mnIntervenant",
        "bpIntervenant",
        "immoIntervenant",
        "rueIntervenant",
        "lieuIntervenant",
        "villeIntervenant",
        "depIntervenant",
        "commentairesIntervenant",
        "service",
        "contact"
    })
    public static class Emetteur {

        @XmlElement(name = "CdIntervenant", required = true)
        protected CdIntervenant cdIntervenant;
        @XmlElement(name = "NomIntervenant")
        protected NomIntervenant nomIntervenant;
        @XmlElement(name = "MnIntervenant")
        protected MnIntervenant mnIntervenant;
        @XmlElement(name = "BpIntervenant")
        protected BpIntervenant bpIntervenant;
        @XmlElement(name = "ImmoIntervenant")
        protected ImmoIntervenant immoIntervenant;
        @XmlElement(name = "RueIntervenant")
        protected RueIntervenant rueIntervenant;
        @XmlElement(name = "LieuIntervenant")
        protected LieuIntervenant lieuIntervenant;
        @XmlElement(name = "VilleIntervenant")
        protected VilleIntervenant villeIntervenant;
        @XmlElement(name = "DepIntervenant")
        protected DepIntervenant depIntervenant;
        @XmlElement(name = "CommentairesIntervenant")
        protected CommentairesIntervenant commentairesIntervenant;
        @XmlElement(name = "Service")
        protected Scenario.Emetteur.Service service;
        @XmlElement(name = "Contact")
        protected Scenario.Emetteur.Contact contact;

        /**
         * Gets the value of the cdIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link CdIntervenant }
         *     
         */
        public CdIntervenant getCdIntervenant() {
            return cdIntervenant;
        }

        /**
         * Sets the value of the cdIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link CdIntervenant }
         *     
         */
        public void setCdIntervenant(CdIntervenant value) {
            this.cdIntervenant = value;
        }

        /**
         * Gets the value of the nomIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link NomIntervenant }
         *     
         */
        public NomIntervenant getNomIntervenant() {
            return nomIntervenant;
        }

        /**
         * Sets the value of the nomIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link NomIntervenant }
         *     
         */
        public void setNomIntervenant(NomIntervenant value) {
            this.nomIntervenant = value;
        }

        /**
         * Gets the value of the mnIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link MnIntervenant }
         *     
         */
        public MnIntervenant getMnIntervenant() {
            return mnIntervenant;
        }

        /**
         * Sets the value of the mnIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link MnIntervenant }
         *     
         */
        public void setMnIntervenant(MnIntervenant value) {
            this.mnIntervenant = value;
        }

        /**
         * Gets the value of the bpIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link BpIntervenant }
         *     
         */
        public BpIntervenant getBpIntervenant() {
            return bpIntervenant;
        }

        /**
         * Sets the value of the bpIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link BpIntervenant }
         *     
         */
        public void setBpIntervenant(BpIntervenant value) {
            this.bpIntervenant = value;
        }

        /**
         * Gets the value of the immoIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link ImmoIntervenant }
         *     
         */
        public ImmoIntervenant getImmoIntervenant() {
            return immoIntervenant;
        }

        /**
         * Sets the value of the immoIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImmoIntervenant }
         *     
         */
        public void setImmoIntervenant(ImmoIntervenant value) {
            this.immoIntervenant = value;
        }

        /**
         * Gets the value of the rueIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link RueIntervenant }
         *     
         */
        public RueIntervenant getRueIntervenant() {
            return rueIntervenant;
        }

        /**
         * Sets the value of the rueIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link RueIntervenant }
         *     
         */
        public void setRueIntervenant(RueIntervenant value) {
            this.rueIntervenant = value;
        }

        /**
         * Gets the value of the lieuIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link LieuIntervenant }
         *     
         */
        public LieuIntervenant getLieuIntervenant() {
            return lieuIntervenant;
        }

        /**
         * Sets the value of the lieuIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link LieuIntervenant }
         *     
         */
        public void setLieuIntervenant(LieuIntervenant value) {
            this.lieuIntervenant = value;
        }

        /**
         * Gets the value of the villeIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link VilleIntervenant }
         *     
         */
        public VilleIntervenant getVilleIntervenant() {
            return villeIntervenant;
        }

        /**
         * Sets the value of the villeIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link VilleIntervenant }
         *     
         */
        public void setVilleIntervenant(VilleIntervenant value) {
            this.villeIntervenant = value;
        }

        /**
         * Gets the value of the depIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link DepIntervenant }
         *     
         */
        public DepIntervenant getDepIntervenant() {
            return depIntervenant;
        }

        /**
         * Sets the value of the depIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link DepIntervenant }
         *     
         */
        public void setDepIntervenant(DepIntervenant value) {
            this.depIntervenant = value;
        }

        /**
         * Gets the value of the commentairesIntervenant property.
         * 
         * @return
         *     possible object is
         *     {@link CommentairesIntervenant }
         *     
         */
        public CommentairesIntervenant getCommentairesIntervenant() {
            return commentairesIntervenant;
        }

        /**
         * Sets the value of the commentairesIntervenant property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommentairesIntervenant }
         *     
         */
        public void setCommentairesIntervenant(CommentairesIntervenant value) {
            this.commentairesIntervenant = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link Scenario.Emetteur.Service }
         *     
         */
        public Scenario.Emetteur.Service getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link Scenario.Emetteur.Service }
         *     
         */
        public void setService(Scenario.Emetteur.Service value) {
            this.service = value;
        }

        /**
         * Gets the value of the contact property.
         * 
         * @return
         *     possible object is
         *     {@link Scenario.Emetteur.Contact }
         *     
         */
        public Scenario.Emetteur.Contact getContact() {
            return contact;
        }

        /**
         * Sets the value of the contact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Scenario.Emetteur.Contact }
         *     
         */
        public void setContact(Scenario.Emetteur.Contact value) {
            this.contact = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nomContact"
        })
        public static class Contact {

            @XmlElement(name = "NomContact")
            protected NomContact nomContact;

            /**
             * Gets the value of the nomContact property.
             * 
             * @return
             *     possible object is
             *     {@link NomContact }
             *     
             */
            public NomContact getNomContact() {
                return nomContact;
            }

            /**
             * Sets the value of the nomContact property.
             * 
             * @param value
             *     allowed object is
             *     {@link NomContact }
             *     
             */
            public void setNomContact(NomContact value) {
                this.nomContact = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nomService"
        })
        public static class Service {

            @XmlElement(name = "NomService")
            protected NomService nomService;

            /**
             * Gets the value of the nomService property.
             * 
             * @return
             *     possible object is
             *     {@link NomService }
             *     
             */
            public NomService getNomService() {
                return nomService;
            }

            /**
             * Sets the value of the nomService property.
             * 
             * @param value
             *     allowed object is
             *     {@link NomService }
             *     
             */
            public void setNomService(NomService value) {
                this.nomService = value;
            }

        }

    }

}
