package fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Thu Nov 04 16:16:39 CET 2010
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", name = "DocumentService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocumentService {

    @RequestWrapper(localName = "save", targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.Document arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.GetDocument")
    @WebMethod
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.GetDocumentResponse")
    public fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.Document getDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "allDocuments", targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.AllDocuments")
    @WebMethod
    @ResponseWrapper(localName = "allDocumentsResponse", targetNamespace = "http://service.spring.wssecurity.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.AllDocumentsResponse")
    public java.util.List<fr.urssaf.image.commons.webservice.wssecurity.spring.client.modele.Document> allDocuments();
}
