//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.composantstypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.DescriptifErreur;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.LocationErreur;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.NomScenario;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.ReferenceFichier;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.ReferenceFichierEnvoi;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.ActivitesIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.AuteurIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.BpIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.CPIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.CdSIRETRattacheIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.CdService;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.CommentairesIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.DepIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.FaxContact;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.FonctionContact;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.ImmoIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.LieuIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.MnIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomContact;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomInternationalIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.NomService;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.RueIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.StIntervenant;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.TelephoneContact;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref.VilleIntervenant;


/**
 * <p>Java class for TextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}simpleLink"/>
 *       &lt;attGroup ref="{http://xml.sandre.eaufrance.fr/Composants/1}commonAttributes"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType", propOrder = {
    "value"
})
@XmlSeeAlso({
    DescriptifErreur.class,
    ReferenceFichier.class,
    NomScenario.class,
    ReferenceFichierEnvoi.class,
    LocationErreur.class,
    NomContact.class,
    FonctionContact.class,
    NomService.class,
    RueIntervenant.class,
    MnIntervenant.class,
    FaxContact.class,
    CommentairesIntervenant.class,
    AuteurIntervenant.class,
    NomInternationalIntervenant.class,
    VilleIntervenant.class,
    LieuIntervenant.class,
    BpIntervenant.class,
    TelephoneContact.class,
    CdService.class,
    CdSIRETRattacheIntervenant.class,
    NomIntervenant.class,
    ActivitesIntervenant.class,
    StIntervenant.class,
    CPIntervenant.class,
    DepIntervenant.class,
    ImmoIntervenant.class
})
public class TextType {

    @XmlValue
    protected String value;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String type;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String href;
    @XmlAttribute(name = "role", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String roleAttr;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String arcrole;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String show;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String actuate;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String language;
    @XmlAttribute(name = "Role", namespace = "http://xml.sandre.eaufrance.fr/Composants/1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String role;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the roleAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleAttr() {
        return roleAttr;
    }

    /**
     * Sets the value of the roleAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleAttr(String value) {
        this.roleAttr = value;
    }

    /**
     * Gets the value of the arcrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
