//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:23:26 AM CET 
//


package fr.gouv.ae.archive.draft.standard_echange_v0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import fr.gouv.ae.archive.draft.standard_echange_v0_2.qualifieddatatype._1.ArchivesIDType;
import fr.gouv.ae.archive.draft.standard_echange_v0_2.qualifieddatatype._1.CodeLanguageType;
import un.unece.uncefact.data.standard.unqualifieddatatype._6.MeasureType;
import un.unece.uncefact.data.standard.unqualifieddatatype._6.TextType;


/**
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;AAES000002&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Acronym xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ABIE&lt;/ccts:Acronym&gt;
 * </pre>
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ContentDescription&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Version xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:Version&gt;
 * </pre>
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Informations sur le contenu de l'archive ou l'objet.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:ObjectClassTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ContentDescription&lt;/ccts:ObjectClassTerm&gt;
 * </pre>
 * 
 *                                 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:QualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="fr:gouv:ae:archive:draft:standard_echange_v0.2" xmlns:qdt="fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ContentDescription&lt;/ccts:QualifierTerm&gt;
 * </pre>
 * 
 *                         
 * 
 * <p>Java class for ContentDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustodialHistory" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}TextType" minOccurs="0"/>
 *         &lt;element name="Description" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}TextType" minOccurs="0"/>
 *         &lt;element name="FilePlanPosition" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1}ArchivesIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Format" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Language" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1}CodeLanguageType" maxOccurs="unbounded"/>
 *         &lt;element name="LatestDate" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}DateType" minOccurs="0"/>
 *         &lt;element name="OldestDate" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}DateType" minOccurs="0"/>
 *         &lt;element name="OtherDescriptiveData" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}TextType" minOccurs="0"/>
 *         &lt;element name="RelatedObjectReference" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2:QualifiedDataType:1}ArchivesIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Size" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:6}MeasureType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OriginatingAgency" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2}OrganizationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Repository" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2}OrganizationType" minOccurs="0"/>
 *         &lt;element name="ContentDescriptive" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2}KeywordType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccessRestriction" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2}AccessRestrictionRulesType" minOccurs="0"/>
 *         &lt;element name="OtherMetadata" type="{fr:gouv:ae:archive:draft:standard_echange_v0.2}OtherMetadataType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentDescriptionType", propOrder = {
    "custodialHistory",
    "description",
    "filePlanPosition",
    "format",
    "language",
    "latestDate",
    "oldestDate",
    "otherDescriptiveData",
    "relatedObjectReference",
    "size",
    "originatingAgency",
    "repository",
    "contentDescriptive",
    "accessRestriction",
    "otherMetadata"
})
public class ContentDescriptionType {

    @XmlElement(name = "CustodialHistory")
    protected TextType custodialHistory;
    @XmlElement(name = "Description")
    protected TextType description;
    @XmlElement(name = "FilePlanPosition")
    protected List<ArchivesIDType> filePlanPosition;
    @XmlElement(name = "Format")
    protected List<TextType> format;
    @XmlElement(name = "Language", required = true)
    protected List<CodeLanguageType> language;
    @XmlElement(name = "LatestDate")
    protected XMLGregorianCalendar latestDate;
    @XmlElement(name = "OldestDate")
    protected XMLGregorianCalendar oldestDate;
    @XmlElement(name = "OtherDescriptiveData")
    protected TextType otherDescriptiveData;
    @XmlElement(name = "RelatedObjectReference")
    protected List<ArchivesIDType> relatedObjectReference;
    @XmlElement(name = "Size")
    protected List<MeasureType> size;
    @XmlElement(name = "OriginatingAgency")
    protected List<OrganizationType> originatingAgency;
    @XmlElement(name = "Repository")
    protected OrganizationType repository;
    @XmlElement(name = "ContentDescriptive")
    protected List<KeywordType> contentDescriptive;
    @XmlElement(name = "AccessRestriction")
    protected AccessRestrictionRulesType accessRestriction;
    @XmlElement(name = "OtherMetadata")
    protected OtherMetadataType otherMetadata;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the custodialHistory property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getCustodialHistory() {
        return custodialHistory;
    }

    /**
     * Sets the value of the custodialHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setCustodialHistory(TextType value) {
        this.custodialHistory = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setDescription(TextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the filePlanPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filePlanPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilePlanPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArchivesIDType }
     * 
     * 
     */
    public List<ArchivesIDType> getFilePlanPosition() {
        if (filePlanPosition == null) {
            filePlanPosition = new ArrayList<ArchivesIDType>();
        }
        return this.filePlanPosition;
    }

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getFormat() {
        if (format == null) {
            format = new ArrayList<TextType>();
        }
        return this.format;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeLanguageType }
     * 
     * 
     */
    public List<CodeLanguageType> getLanguage() {
        if (language == null) {
            language = new ArrayList<CodeLanguageType>();
        }
        return this.language;
    }

    /**
     * Gets the value of the latestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLatestDate() {
        return latestDate;
    }

    /**
     * Sets the value of the latestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLatestDate(XMLGregorianCalendar value) {
        this.latestDate = value;
    }

    /**
     * Gets the value of the oldestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOldestDate() {
        return oldestDate;
    }

    /**
     * Sets the value of the oldestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOldestDate(XMLGregorianCalendar value) {
        this.oldestDate = value;
    }

    /**
     * Gets the value of the otherDescriptiveData property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getOtherDescriptiveData() {
        return otherDescriptiveData;
    }

    /**
     * Sets the value of the otherDescriptiveData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setOtherDescriptiveData(TextType value) {
        this.otherDescriptiveData = value;
    }

    /**
     * Gets the value of the relatedObjectReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedObjectReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedObjectReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArchivesIDType }
     * 
     * 
     */
    public List<ArchivesIDType> getRelatedObjectReference() {
        if (relatedObjectReference == null) {
            relatedObjectReference = new ArrayList<ArchivesIDType>();
        }
        return this.relatedObjectReference;
    }

    /**
     * Gets the value of the size property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the size property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureType }
     * 
     * 
     */
    public List<MeasureType> getSize() {
        if (size == null) {
            size = new ArrayList<MeasureType>();
        }
        return this.size;
    }

    /**
     * Gets the value of the originatingAgency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originatingAgency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginatingAgency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationType }
     * 
     * 
     */
    public List<OrganizationType> getOriginatingAgency() {
        if (originatingAgency == null) {
            originatingAgency = new ArrayList<OrganizationType>();
        }
        return this.originatingAgency;
    }

    /**
     * Gets the value of the repository property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *     
     */
    public OrganizationType getRepository() {
        return repository;
    }

    /**
     * Sets the value of the repository property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *     
     */
    public void setRepository(OrganizationType value) {
        this.repository = value;
    }

    /**
     * Gets the value of the contentDescriptive property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentDescriptive property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentDescriptive().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeywordType }
     * 
     * 
     */
    public List<KeywordType> getContentDescriptive() {
        if (contentDescriptive == null) {
            contentDescriptive = new ArrayList<KeywordType>();
        }
        return this.contentDescriptive;
    }

    /**
     * Gets the value of the accessRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link AccessRestrictionRulesType }
     *     
     */
    public AccessRestrictionRulesType getAccessRestriction() {
        return accessRestriction;
    }

    /**
     * Sets the value of the accessRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessRestrictionRulesType }
     *     
     */
    public void setAccessRestriction(AccessRestrictionRulesType value) {
        this.accessRestriction = value;
    }

    /**
     * Gets the value of the otherMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link OtherMetadataType }
     *     
     */
    public OtherMetadataType getOtherMetadata() {
        return otherMetadata;
    }

    /**
     * Sets the value of the otherMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherMetadataType }
     *     
     */
    public void setOtherMetadata(OtherMetadataType value) {
        this.otherMetadata = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
