package fr.urssaf.image.commons.webservice.exemple.document.modele;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon May 31 18:51:14 CEST 2010
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", name = "DocService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "allDocuments", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.AllDocuments")
    @WebMethod
    @ResponseWrapper(localName = "allDocumentsResponse", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.AllDocumentsResponse")
    public java.util.List<fr.urssaf.image.commons.webservice.exemple.document.modele.Document> allDocuments();
}
