package fr.urssaf.image.commons.webservice.exemple.document.modele;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Thu Nov 04 13:36:10 CET 2010
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", name = "DocService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "allDocuments", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.AllDocuments")
    @WebMethod
    @ResponseWrapper(localName = "allDocumentsResponse", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.AllDocumentsResponse")
    public java.util.List<fr.urssaf.image.commons.webservice.exemple.document.modele.Document> allDocuments();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDocument", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.GetDocument")
    @WebMethod
    @ResponseWrapper(localName = "getDocumentResponse", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.GetDocumentResponse")
    public fr.urssaf.image.commons.webservice.exemple.document.modele.Document getDocument(
        @WebParam(name = "id", targetNamespace = "")
        int id
    );

    @RequestWrapper(localName = "save", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://document.service.exemple.spring.webservice.commons.image.urssaf.fr/", className = "fr.urssaf.image.commons.webservice.exemple.document.modele.SaveResponse")
    public void save(
        @WebParam(name = "document", targetNamespace = "")
        fr.urssaf.image.commons.webservice.exemple.document.modele.Document document
    );
}
