//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 12:10:25 PM CET 
//


package fr.urssaf.image.sae.integration.ihmweb.modele.listetests;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListeCasTestsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListeCasTestsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CasTest" type="{http://www.cirtil.fr/saeIntegration/tests}CasTestType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListeCasTestsType", propOrder = {
    "casTest"
})
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class ListeCasTestsType {

    @XmlElement(name = "CasTest")
    protected List<CasTestType> casTest;

    /**
     * Gets the value of the casTest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the casTest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCasTest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CasTestType }
     * 
     * 
     */
    public List<CasTestType> getCasTest() {
        if (casTest == null) {
            casTest = new ArrayList<CasTestType>();
        }
        return this.casTest;
    }

}
