//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 12:10:25 PM CET 
//


package fr.urssaf.image.sae.integration.ihmweb.modele.listetests;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.urssaf.image.sae.integration.ihmweb.modele.listetests package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
// CHECKSTYLE:OFF
@SuppressWarnings("all")
public class ObjectFactory {

    private final static QName _Tests_QNAME = new QName("http://www.cirtil.fr/saeIntegration/tests", "Tests");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.urssaf.image.sae.integration.ihmweb.modele.listetests
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListeCategoriesType }
     * 
     */
    public ListeCategoriesType createListeCategoriesType() {
        return new ListeCategoriesType();
    }

    /**
     * Create an instance of {@link CategorieType }
     * 
     */
    public CategorieType createCategorieType() {
        return new CategorieType();
    }

    /**
     * Create an instance of {@link CasTestType }
     * 
     */
    public CasTestType createCasTestType() {
        return new CasTestType();
    }

    /**
     * Create an instance of {@link ListeCasTestsType }
     * 
     */
    public ListeCasTestsType createListeCasTestsType() {
        return new ListeCasTestsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListeCategoriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cirtil.fr/saeIntegration/tests", name = "Tests")
    public JAXBElement<ListeCategoriesType> createTests(ListeCategoriesType value) {
        return new JAXBElement<ListeCategoriesType>(_Tests_QNAME, ListeCategoriesType.class, null, value);
    }

}
