//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:23:26 AM CET 
//


package un.unece.uncefact.codelist.draft.daf.documenttypecode._2009_08_18;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CDO"/>
 *     &lt;enumeration value="RI"/>
 *     &lt;enumeration value="RISTR"/>
 *     &lt;enumeration value="RISEM"/>
 *     &lt;enumeration value="PDI"/>
 *     &lt;enumeration value="PDIPRO"/>
 *     &lt;enumeration value="PDIREF"/>
 *     &lt;enumeration value="PDIFIX"/>
 *     &lt;enumeration value="PDICTX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DocumentTypeCodeType", namespace = "urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18")
@XmlEnum
public enum DocumentTypeCodeType {


    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Content Data Object&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    CDO,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Representation Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    RI,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Structure Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    RISTR,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Semantic Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    RISEM,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Preservation Description Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    PDI,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Provenance Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    PDIPRO,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Reference Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    PDIREF,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Fixity Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    PDIFIX,

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns="urn:un:unece:uncefact:codelist:draft:daf:documentTypeCode:2009-08-18" xmlns:clmDAFDocumentTypeCode="urn:un:unece:uncefact:codelist:draft:DAF:documentTypeCode:2009-08-18" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Context Information&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 					
     * 
     */
    PDICTX;

    public String value() {
        return name();
    }

    public static DocumentTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
