package fr.urssaf.image.commons.webservice.exemple.ssl.document.modele;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.0
 * Fri Nov 05 10:31:11 CET 2010
 * Generated source version: 2.3.0
 * 
 */
 
@WebService(targetNamespace = "http://localhost/", name = "HelloServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloServicePortType {

    @WebResult(name = "multiplieResponse", targetNamespace = "http://localhost/", partName = "parameters")
    @WebMethod(action = "http://localhost/#multiplie")
    public MultiplieResponseType multiplie(
        @WebParam(partName = "parameters", name = "multiplie", targetNamespace = "http://localhost/")
        MultiplieRequestType parameters
    );

    @WebResult(name = "bonjourResponse", targetNamespace = "http://localhost/", partName = "parameters")
    @WebMethod(action = "http://localhost/#bonjour")
    public BonjourResponseType bonjour(
        @WebParam(partName = "parameters", name = "bonjour", targetNamespace = "http://localhost/")
        BonjourRequestType parameters
    );
}
