//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.composantstypes.TextType;


/**
 * Liste indicative et
 *             non exhautive des différentes compétences de l'intervenant.
 * 
 *             Quand l'intervenant possède plusieurs domaines d'activité,
 *             leur libellé sera séparé par une virgule.
 * 
 *             Cette information est fournie par le ou les organismes qui déposent une
 *             demande d'enregistrement d'un intervenant auprès du SANDRE
 *             dans le cas d'absence du code SIRET, information qui peut
 *             être complétée par les mises-à-jour successives de la fiche
 *             descriptive de l'intervenant. 
 * 
 * <p>Java class for ActivitesIntervenant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivitesIntervenant">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://xml.sandre.eaufrance.fr/Composants/1>TextType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivitesIntervenant")
public class ActivitesIntervenant
    extends TextType
{


}
