//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tout utilisateur de
 *             la liste SANDRE des intervenants peut dresser pour ses
 *             propres besoins une liste de personnes physiques ou
 *             'contacts' représentant l'intervenant dans le cadre d'une ou
 *             plusieurs fonctions (Directeur général, Directeur de
 *             laboratoire, responsable administratif, correspondant
 *             technique, ...)
 * 
 *             La liste des contacts n'est pas gérée au niveau national. Il s'agit
 *             d'un outil (en termes de modélisation) mis à disposition par
 *             le SANDRE à l'ensemble des producteurs qui seront
 *             responsables des listes qu'ils gérent en interne à leur
 *             organisation.
 * 
 * <p>Java class for Contact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CdContact" type="{http://xml.sandre.eaufrance.fr/int/2}CdContact"/>
 *         &lt;element name="NomContact" type="{http://xml.sandre.eaufrance.fr/int/2}NomContact" minOccurs="0"/>
 *         &lt;element name="FonctionContact" type="{http://xml.sandre.eaufrance.fr/int/2}FonctionContact" minOccurs="0"/>
 *         &lt;element name="TelephoneContact" type="{http://xml.sandre.eaufrance.fr/int/2}TelephoneContact" minOccurs="0"/>
 *         &lt;element name="FaxContact" type="{http://xml.sandre.eaufrance.fr/int/2}FaxContact" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact", propOrder = {
    "cdContact",
    "nomContact",
    "fonctionContact",
    "telephoneContact",
    "faxContact"
})
public class Contact {

    @XmlElement(name = "CdContact", required = true)
    protected CdContact cdContact;
    @XmlElement(name = "NomContact")
    protected NomContact nomContact;
    @XmlElement(name = "FonctionContact")
    protected FonctionContact fonctionContact;
    @XmlElement(name = "TelephoneContact")
    protected TelephoneContact telephoneContact;
    @XmlElement(name = "FaxContact")
    protected FaxContact faxContact;

    /**
     * Gets the value of the cdContact property.
     * 
     * @return
     *     possible object is
     *     {@link CdContact }
     *     
     */
    public CdContact getCdContact() {
        return cdContact;
    }

    /**
     * Sets the value of the cdContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdContact }
     *     
     */
    public void setCdContact(CdContact value) {
        this.cdContact = value;
    }

    /**
     * Gets the value of the nomContact property.
     * 
     * @return
     *     possible object is
     *     {@link NomContact }
     *     
     */
    public NomContact getNomContact() {
        return nomContact;
    }

    /**
     * Sets the value of the nomContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomContact }
     *     
     */
    public void setNomContact(NomContact value) {
        this.nomContact = value;
    }

    /**
     * Gets the value of the fonctionContact property.
     * 
     * @return
     *     possible object is
     *     {@link FonctionContact }
     *     
     */
    public FonctionContact getFonctionContact() {
        return fonctionContact;
    }

    /**
     * Sets the value of the fonctionContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link FonctionContact }
     *     
     */
    public void setFonctionContact(FonctionContact value) {
        this.fonctionContact = value;
    }

    /**
     * Gets the value of the telephoneContact property.
     * 
     * @return
     *     possible object is
     *     {@link TelephoneContact }
     *     
     */
    public TelephoneContact getTelephoneContact() {
        return telephoneContact;
    }

    /**
     * Sets the value of the telephoneContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephoneContact }
     *     
     */
    public void setTelephoneContact(TelephoneContact value) {
        this.telephoneContact = value;
    }

    /**
     * Gets the value of the faxContact property.
     * 
     * @return
     *     possible object is
     *     {@link FaxContact }
     *     
     */
    public FaxContact getFaxContact() {
        return faxContact;
    }

    /**
     * Sets the value of the faxContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaxContact }
     *     
     */
    public void setFaxContact(FaxContact value) {
        this.faxContact = value;
    }

}
