//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.composantstypes.DateTimeType;


/**
 * La date de la
 *             dernière mise-à-jour de l'intervenant est la date exprimée
 *             au jour près, de la dernière mise-à-jour validée des
 *             informations portées sur la fiche de description de
 *             l'intervenant.
 * 
 *             Cet attribut est inutilisé en dehors de la liste SANDRE.
 * 
 *             La liste des intervenants est administrée par le SANDRE qui en a la
 *             responsabilité.
 * 
 * <p>Java class for DateMajIntervenant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateMajIntervenant">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://xml.sandre.eaufrance.fr/Composants/1>DateTimeType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateMajIntervenant")
public class DateMajIntervenant
    extends DateTimeType
{


}
