//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.composantstypes.DateType;


/**
 * La date de création
 *             de l'intervenant est une date exprimée au jour près, à
 *             laquelle un intervenant a été enregistré par le SANDRE, avec
 *             le statut de code provisoire, dans la liste nationale des
 *             intervenants (cf. statut de l'intervenant).
 * 
 *             Cet attribut est inutilisé en dehors de la liste SANDRE.
 * 
 *             L'affectation d'une date de création à un intervenant relève de la responsabilité
 *             du SANDRE.
 * 
 * <p>Java class for DateCreationIntervenant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateCreationIntervenant">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://xml.sandre.eaufrance.fr/Composants/1>DateType">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateCreationIntervenant")
public class DateCreationIntervenant
    extends DateType
{


}
