//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Les intervenants
 *             sont tous les organismes ayant un ou plusieurs rôle(s) en
 *             tant qu’acteur de l’eau et qui sont référencés dans les
 *             bases de données respectant le formalisme du SANDRE. Ils
 *             sont identifiés dans les échanges de données par leur code
 *             SIRET. Quand ce dernier ne peut pas exister car
 *             l'intervenant ne rentre pas dans le domaine d'application du
 *             registre national ou lorsque ce code ne permet pas
 *             d’identifier de manière univoque l’intervenant (cas des
 *             structures incluses dans une structure plus générale), il
 *             est alors identifié par son code SANDRE.
 * 
 *             Ils se partagent entre plusieurs catégories dont :
 *             - laboratoire d'analyse,
 *             - préleveur,
 *             - opérateur en hydrométrie,
 *             - laboratoire d'hydrobiologie,
 *             - organisme chargé de la police des eaux,
 *             - producteur/ gestionnaire,
 *             - …
 * 
 *             Deux informations sont utilisées pour identifier un intervenant : son
 *             code et le code SIRET de l’organisme auquel il est rattaché
 *             :
 *             - Cas 1 : l’organisme est SIRETE, par exemple un laboratoire. Le code
 *             SIRET est utilisé, aucun code SANDRE n’est indiqué.
 *             L’attribut “ code SIRET de l’organisme auquel est rattaché
 *             l’intervenant ” n’est pas rempli,
 *             - Cas 2 : l’organisme n’a pas de code SIRET, dans ce cas, il est
 *             attribué un code SANDRE. L’attribut “ code SIRET de
 *             l’organisme auquel est rattaché l’intervenant ” n’est pas
 *             rempli,
 *             - Cas 3 : l’organisme n’a pas de code SIRET en tant qu’établissement
 *             mais est rattaché à une structure, par exemple le SATESE
 *             rattaché au Conseil Général. Dans ce cas, il est attribué un
 *             code SANDRE et l’attribut “ code SIRET de l’organisme auquel
 *             est rattaché l’intervenant ” est rempli avec le code SIRET,
 *             dans l’exemple, celui du Conseil Général.
 * 
 *             La liste nationale des codes SANDRE des intervenants est établie sous
 *             la responsabilité du SANDRE. Le code SIRET est établi par
 *             l'INSEE.
 * 
 * <p>Java class for Intervenant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Intervenant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CdIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CdIntervenant"/>
 *         &lt;element name="NomIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}NomIntervenant" minOccurs="0"/>
 *         &lt;element name="StIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}StIntervenant" minOccurs="0"/>
 *         &lt;element name="DateCreationIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DateCreationIntervenant" minOccurs="0"/>
 *         &lt;element name="DateMajIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DateMajIntervenant" minOccurs="0"/>
 *         &lt;element name="AuteurIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}AuteurIntervenant" minOccurs="0"/>
 *         &lt;element name="MnIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}MnIntervenant" minOccurs="0"/>
 *         &lt;element name="BpIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}BpIntervenant" minOccurs="0"/>
 *         &lt;element name="ImmoIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}ImmoIntervenant" minOccurs="0"/>
 *         &lt;element name="RueIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}RueIntervenant" minOccurs="0"/>
 *         &lt;element name="LieuIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}LieuIntervenant" minOccurs="0"/>
 *         &lt;element name="VilleIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}VilleIntervenant" minOccurs="0"/>
 *         &lt;element name="DepIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}DepIntervenant" minOccurs="0"/>
 *         &lt;element name="CommentairesIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CommentairesIntervenant" minOccurs="0"/>
 *         &lt;element name="ActivitesIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}ActivitesIntervenant" minOccurs="0"/>
 *         &lt;element name="CPIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CPIntervenant" minOccurs="0"/>
 *         &lt;element name="NomInternationalIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}NomInternationalIntervenant" minOccurs="0"/>
 *         &lt;element name="CdSIRETRattacheIntervenant" type="{http://xml.sandre.eaufrance.fr/int/2}CdSIRETRattacheIntervenant" minOccurs="0"/>
 *         &lt;element name="Service" type="{http://xml.sandre.eaufrance.fr/int/2}Service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Contact" type="{http://xml.sandre.eaufrance.fr/int/2}Contact" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Intervenant", propOrder = {
    "cdIntervenant",
    "nomIntervenant",
    "stIntervenant",
    "dateCreationIntervenant",
    "dateMajIntervenant",
    "auteurIntervenant",
    "mnIntervenant",
    "bpIntervenant",
    "immoIntervenant",
    "rueIntervenant",
    "lieuIntervenant",
    "villeIntervenant",
    "depIntervenant",
    "commentairesIntervenant",
    "activitesIntervenant",
    "cpIntervenant",
    "nomInternationalIntervenant",
    "cdSIRETRattacheIntervenant",
    "service",
    "contact"
})
public class Intervenant {

    @XmlElement(name = "CdIntervenant", required = true)
    protected CdIntervenant cdIntervenant;
    @XmlElement(name = "NomIntervenant")
    protected NomIntervenant nomIntervenant;
    @XmlElement(name = "StIntervenant")
    protected StIntervenant stIntervenant;
    @XmlElement(name = "DateCreationIntervenant")
    protected DateCreationIntervenant dateCreationIntervenant;
    @XmlElement(name = "DateMajIntervenant")
    protected DateMajIntervenant dateMajIntervenant;
    @XmlElement(name = "AuteurIntervenant")
    protected AuteurIntervenant auteurIntervenant;
    @XmlElement(name = "MnIntervenant")
    protected MnIntervenant mnIntervenant;
    @XmlElement(name = "BpIntervenant")
    protected BpIntervenant bpIntervenant;
    @XmlElement(name = "ImmoIntervenant")
    protected ImmoIntervenant immoIntervenant;
    @XmlElement(name = "RueIntervenant")
    protected RueIntervenant rueIntervenant;
    @XmlElement(name = "LieuIntervenant")
    protected LieuIntervenant lieuIntervenant;
    @XmlElement(name = "VilleIntervenant")
    protected VilleIntervenant villeIntervenant;
    @XmlElement(name = "DepIntervenant")
    protected DepIntervenant depIntervenant;
    @XmlElement(name = "CommentairesIntervenant")
    protected CommentairesIntervenant commentairesIntervenant;
    @XmlElement(name = "ActivitesIntervenant")
    protected ActivitesIntervenant activitesIntervenant;
    @XmlElement(name = "CPIntervenant")
    protected CPIntervenant cpIntervenant;
    @XmlElement(name = "NomInternationalIntervenant")
    protected NomInternationalIntervenant nomInternationalIntervenant;
    @XmlElement(name = "CdSIRETRattacheIntervenant")
    protected CdSIRETRattacheIntervenant cdSIRETRattacheIntervenant;
    @XmlElement(name = "Service")
    protected List<Service> service;
    @XmlElement(name = "Contact")
    protected List<Contact> contact;

    /**
     * Gets the value of the cdIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link CdIntervenant }
     *     
     */
    public CdIntervenant getCdIntervenant() {
        return cdIntervenant;
    }

    /**
     * Sets the value of the cdIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdIntervenant }
     *     
     */
    public void setCdIntervenant(CdIntervenant value) {
        this.cdIntervenant = value;
    }

    /**
     * Gets the value of the nomIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link NomIntervenant }
     *     
     */
    public NomIntervenant getNomIntervenant() {
        return nomIntervenant;
    }

    /**
     * Sets the value of the nomIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomIntervenant }
     *     
     */
    public void setNomIntervenant(NomIntervenant value) {
        this.nomIntervenant = value;
    }

    /**
     * Gets the value of the stIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link StIntervenant }
     *     
     */
    public StIntervenant getStIntervenant() {
        return stIntervenant;
    }

    /**
     * Sets the value of the stIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link StIntervenant }
     *     
     */
    public void setStIntervenant(StIntervenant value) {
        this.stIntervenant = value;
    }

    /**
     * Gets the value of the dateCreationIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link DateCreationIntervenant }
     *     
     */
    public DateCreationIntervenant getDateCreationIntervenant() {
        return dateCreationIntervenant;
    }

    /**
     * Sets the value of the dateCreationIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCreationIntervenant }
     *     
     */
    public void setDateCreationIntervenant(DateCreationIntervenant value) {
        this.dateCreationIntervenant = value;
    }

    /**
     * Gets the value of the dateMajIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link DateMajIntervenant }
     *     
     */
    public DateMajIntervenant getDateMajIntervenant() {
        return dateMajIntervenant;
    }

    /**
     * Sets the value of the dateMajIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateMajIntervenant }
     *     
     */
    public void setDateMajIntervenant(DateMajIntervenant value) {
        this.dateMajIntervenant = value;
    }

    /**
     * Gets the value of the auteurIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link AuteurIntervenant }
     *     
     */
    public AuteurIntervenant getAuteurIntervenant() {
        return auteurIntervenant;
    }

    /**
     * Sets the value of the auteurIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuteurIntervenant }
     *     
     */
    public void setAuteurIntervenant(AuteurIntervenant value) {
        this.auteurIntervenant = value;
    }

    /**
     * Gets the value of the mnIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link MnIntervenant }
     *     
     */
    public MnIntervenant getMnIntervenant() {
        return mnIntervenant;
    }

    /**
     * Sets the value of the mnIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MnIntervenant }
     *     
     */
    public void setMnIntervenant(MnIntervenant value) {
        this.mnIntervenant = value;
    }

    /**
     * Gets the value of the bpIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link BpIntervenant }
     *     
     */
    public BpIntervenant getBpIntervenant() {
        return bpIntervenant;
    }

    /**
     * Sets the value of the bpIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BpIntervenant }
     *     
     */
    public void setBpIntervenant(BpIntervenant value) {
        this.bpIntervenant = value;
    }

    /**
     * Gets the value of the immoIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link ImmoIntervenant }
     *     
     */
    public ImmoIntervenant getImmoIntervenant() {
        return immoIntervenant;
    }

    /**
     * Sets the value of the immoIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmoIntervenant }
     *     
     */
    public void setImmoIntervenant(ImmoIntervenant value) {
        this.immoIntervenant = value;
    }

    /**
     * Gets the value of the rueIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link RueIntervenant }
     *     
     */
    public RueIntervenant getRueIntervenant() {
        return rueIntervenant;
    }

    /**
     * Sets the value of the rueIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link RueIntervenant }
     *     
     */
    public void setRueIntervenant(RueIntervenant value) {
        this.rueIntervenant = value;
    }

    /**
     * Gets the value of the lieuIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link LieuIntervenant }
     *     
     */
    public LieuIntervenant getLieuIntervenant() {
        return lieuIntervenant;
    }

    /**
     * Sets the value of the lieuIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link LieuIntervenant }
     *     
     */
    public void setLieuIntervenant(LieuIntervenant value) {
        this.lieuIntervenant = value;
    }

    /**
     * Gets the value of the villeIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link VilleIntervenant }
     *     
     */
    public VilleIntervenant getVilleIntervenant() {
        return villeIntervenant;
    }

    /**
     * Sets the value of the villeIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link VilleIntervenant }
     *     
     */
    public void setVilleIntervenant(VilleIntervenant value) {
        this.villeIntervenant = value;
    }

    /**
     * Gets the value of the depIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link DepIntervenant }
     *     
     */
    public DepIntervenant getDepIntervenant() {
        return depIntervenant;
    }

    /**
     * Sets the value of the depIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepIntervenant }
     *     
     */
    public void setDepIntervenant(DepIntervenant value) {
        this.depIntervenant = value;
    }

    /**
     * Gets the value of the commentairesIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link CommentairesIntervenant }
     *     
     */
    public CommentairesIntervenant getCommentairesIntervenant() {
        return commentairesIntervenant;
    }

    /**
     * Sets the value of the commentairesIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentairesIntervenant }
     *     
     */
    public void setCommentairesIntervenant(CommentairesIntervenant value) {
        this.commentairesIntervenant = value;
    }

    /**
     * Gets the value of the activitesIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link ActivitesIntervenant }
     *     
     */
    public ActivitesIntervenant getActivitesIntervenant() {
        return activitesIntervenant;
    }

    /**
     * Sets the value of the activitesIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivitesIntervenant }
     *     
     */
    public void setActivitesIntervenant(ActivitesIntervenant value) {
        this.activitesIntervenant = value;
    }

    /**
     * Gets the value of the cpIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link CPIntervenant }
     *     
     */
    public CPIntervenant getCPIntervenant() {
        return cpIntervenant;
    }

    /**
     * Sets the value of the cpIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPIntervenant }
     *     
     */
    public void setCPIntervenant(CPIntervenant value) {
        this.cpIntervenant = value;
    }

    /**
     * Gets the value of the nomInternationalIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link NomInternationalIntervenant }
     *     
     */
    public NomInternationalIntervenant getNomInternationalIntervenant() {
        return nomInternationalIntervenant;
    }

    /**
     * Sets the value of the nomInternationalIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomInternationalIntervenant }
     *     
     */
    public void setNomInternationalIntervenant(NomInternationalIntervenant value) {
        this.nomInternationalIntervenant = value;
    }

    /**
     * Gets the value of the cdSIRETRattacheIntervenant property.
     * 
     * @return
     *     possible object is
     *     {@link CdSIRETRattacheIntervenant }
     *     
     */
    public CdSIRETRattacheIntervenant getCdSIRETRattacheIntervenant() {
        return cdSIRETRattacheIntervenant;
    }

    /**
     * Sets the value of the cdSIRETRattacheIntervenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdSIRETRattacheIntervenant }
     *     
     */
    public void setCdSIRETRattacheIntervenant(CdSIRETRattacheIntervenant value) {
        this.cdSIRETRattacheIntervenant = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contact }
     * 
     * 
     */
    public List<Contact> getContact() {
        if (contact == null) {
            contact = new ArrayList<Contact>();
        }
        return this.contact;
    }

}
