//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.22 at 10:20:20 AM CET 
//


package fr.urssaf.image.commons.xml.jaxb.exemple.sandre.modele.intref;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Un service est une
 *             structure rattachée à un unique intervenant sur le plan de
 *             l'organisation du travail, et exerçant un ensemble de tâches
 *             spécifiques.
 *             La notion de service interne apparait dès lors qu'un intervenant
 *             définit explicitement son mode d'organisation ainsi que la
 *             répartition des moyens humains et matériels en plusierus
 *             unités distinctes.
 * 
 *             Cette information permet de préciser davantage l'identité des
 *             intervenants mis en jeu.
 * 
 * 
 * <p>Java class for Service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Service">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CdService" type="{http://xml.sandre.eaufrance.fr/int/2}CdService"/>
 *         &lt;element name="NomService" type="{http://xml.sandre.eaufrance.fr/int/2}NomService" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Service", propOrder = {
    "cdService",
    "nomService"
})
public class Service {

    @XmlElement(name = "CdService", required = true)
    protected CdService cdService;
    @XmlElement(name = "NomService")
    protected NomService nomService;

    /**
     * Gets the value of the cdService property.
     * 
     * @return
     *     possible object is
     *     {@link CdService }
     *     
     */
    public CdService getCdService() {
        return cdService;
    }

    /**
     * Sets the value of the cdService property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdService }
     *     
     */
    public void setCdService(CdService value) {
        this.cdService = value;
    }

    /**
     * Gets the value of the nomService property.
     * 
     * @return
     *     possible object is
     *     {@link NomService }
     *     
     */
    public NomService getNomService() {
        return nomService;
    }

    /**
     * Sets the value of the nomService property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomService }
     *     
     */
    public void setNomService(NomService value) {
        this.nomService = value;
    }

}
